### PR TITLE
Major Refactoring

### LINKED ISSUE #27: Handling of longer-than-one graphemes in case of errors
There is a behavior of the tokenizer which I believe is a bug, but might be known or even intended (it ends up helping to catch missing graphemes) -- or I might be missing something obvious (maybe I am building my profiles in a wrong way which is right enough to work in most cases?).

Suppose we have a profile with only three graphemes, `t`, `o`, and `oː`, mapped to their respective IPA values; the profile is loaded the standard way (passing the filename to `__init__`, as `pylexibank` does internally). If we `__call__` the tokenizer on a well-formed string such as `toːt`, it will correctly return `t oː t`. However, if we introduce an error from a string such as `toːt=`, it will return `t o � t �`, failing to match `oː`. This is ultimately due to the way missing entries are handled: `transform()` asks for the `graphemes()`, which are built by calling `self.op.tree.parse()` (tokenizer.py:326); if parsing fails, *all* characters missing from the profile are marked as unknown (tokenizer.py:331). The error is that it should not look for unknown *characters*, but for unknown *graphemes*, which can be composed of more than one character (with all the caveats of first looking for the longer graphemes applying).

There would be a few different ways for solving this (if it is supposed to be solved, that is), but I didn't want to proceed on my own without discussing it, especially because any change to `segments` might unintentionally break a few other operations down the line.

### LINKED ISSUE #32: Using plain "?" as exception marker conflicts with e.g. X-SAMPA
Since `?` is used as regular glyph in X-SAMPA, it shouldn't be used by [default as exception marker](https://github.com/cldf/segments/blob/012c1ffaddf8acca5d3cf6ba1b53df23cbe3d984/src/segments/tokenizer.py#L364).

### PR DESCRIPTION
**Pull request by xrotwang**
- handle segmented data as list of lists internally
- make Tree.parse re-sume parsing after error
- project scaffolding updated

closes #27
closes #32

### CODE REVIEW

**Comment by tresoldi** [comment]
Seems great. You forgot to mention that this also implements `REPLACEMENT_MARKER`, which, while perhaps trivial, is a very positive change in my view. +1 for merging

**Comment by xrotwang** [comment]
I like how this condenses the main functionality into
- [60 lines of `tree.py`](https://github.com/cldf/segments/blob/f1b4cc46bddb3d489559e5ec1e9fcb228d722544/src/segments/tree.py)
- [about 150 lines of `tokenizer.py`](https://github.com/cldf/segments/blob/f1b4cc46bddb3d489559e5ec1e9fcb228d722544/src/segments/tokenizer.py)

If we now add a bunch of tests with cases we encounter in lexibank, there's not too much risc of running into problems with backwards incompatibility, I guess.

**Comment by xrotwang** [comment]
As far as I'm concerned, we could even make orthography profile and input/output from the LingPy tutorial part of the `segments` test suite.

**Comment by xrotwang** [comment]
@bambooforest Ok with merging? From my point of view, this is backwards compatible - although I did remove some non-private methods on `Tokenizer` (which I think should have been private to begin with :) ). If so, this would make 1.2, otherwise I'd also be happy to start the 2.x series with this.

**Comment by LinguList** [comment]
Short question: is the new behavior allowing for lists as lists already implemented here, or do we go on in the way we know? If the former, could you provide a short example for this?

**Comment by xrotwang** [comment]
@bambooforest the external interface has not changed - input and output is still strings; only internally data is handled as lists. I.e. `.split()` and `' '.join()` are only called once and in the outermost layer of code, when receiving input and when creating output.

**Comment by bambooforest** [comment]
@xrotwang - I guess you have to act fast around here :-)  Anyway, thanks for the update.

**Comment by LinguList** [comment]
@xrotwang, I see, and I agree that this is quite important. I remember having some issues with this in the past.

**Comment by xrotwang** [comment]
@bambooforest sorry, for rushing this. I have a long list of stuff depending on this, which made me nervous. I truly think this is backwards compatible, though :)

**Pull request merged**
